spring:
    application:
        name: MaaTech
    datasource:
        driverClassName: org.postgresql.Driver
#        url: jdbc:postgresql://thinly-essential-lorikeet.data-1.use1.tembo.io:5432/MaaTech
        url: jdbc:postgresql://localhost:5432/MaaTech
        username: postgres
        password: he282W0AYkmUNXiD
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                show-sql: true
logging:
    level:
        org:
            hibernate:
                sql: DEBUG
                type:
                    descriptor:
                        sql:
                            basicBinder: TRACE

    flyway:
        baselineOnMigrate: true
api:
    key: AIzaSyC9IMBVBNdpT4vCSAtuHJr946zkEWBf2rw
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}}
