spring:
    application:
        name: MaaTech
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://thinly-essential-lorikeet.data-1.use1.tembo.io:5432/MaaTech
        username: postgres
        password: he282W0AYkmUNXiD
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                show-sql: false
    flyway:
        baselineOnMigrate: true
api:
    key: AIzaSyC9IMBVBNdpT4vCSAtuHJr946zkEWBf2rw
    security:
        token:
            secret: ${JWT_SECRET:my-secret-key}}
