CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE USERS (
    idUser UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
