CREATE TABLE IF NOT EXISTS LIST_ITEMS (
    iduser UUID NOT NULL,
    iditem UUID NOT NULL,
    PRIMARY KEY (iduser, iditem),
    FOREIGN KEY (iduser) REFERENCES USERS(iduser) ON DELETE CASCADE,
    FOREIGN KEY (iditem) REFERENCES ITEMS(iditem) ON DELETE CASCADE
);
