CREATE TABLE LIST_ITEMS (
    idUser UUID NOT NULL,
    idItem UUID NOT NULL,
    PRIMARY KEY (idUser, idItem),
    FOREIGN KEY (idUser) REFERENCES USERS(idUser) ON DELETE CASCADE,
    FOREIGN KEY (idItem) REFERENCES ITEMS(idItem) ON DELETE CASCADE
);
